### ISSUE TITLE
Client uses old input data instead of empty data on registration

### ISSUE THREAD

**Issue by TeemuSavunen** [anttijuu/O3-chat-client#3]
**Describe the bug**
*Before reporting, check that you have the latest version of the ChatClient.*

Client uses old given information when trying to register a new user after already creating one but giving empty information results in the client using the previously given data.

**To Reproduce**
1. Register a new user
2. Use /register to register another user but give empty password/user/email
3. Client either tells user already registered (if new user wasn't specified) or succeed creating new user but with previous data on password/email

**Expected behavior**
Client should say "Must specify all user information for registration!"

**Screenshots**
![regvirhe](https://user-images.githubusercontent.com/77996031/106914952-2e5d4680-670e-11eb-8c9f-dc73d6004fd2.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - JDK version in use openjdk 15.0.1 2020-10-20
 - Version / latest commit of the ChatClient 1.3.2

**Additional context**
Tested my server with curl and it worked as supposed when empty information was given

**Comment by anttijuu** [comment]
Thanks will take a look at some point.

**Comment by anttijuu** [comment]
This will be fixed in the next release with new unit tests.
